# Copyright (C) 2021 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.
---

name: 'Lint and Test Project'

on:
  push:
    branches:
      - 'master'

jobs:
  lint-and-test:
    name: 'Lint and test project'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'

      - name: 'Set up Node environment'
        uses: 'actions/setup-node@v2-beta'
        with:
          node-version: '14'

      - name: 'Set up PHP environment'
        uses: 'shivammathur/setup-php@v2'
        with:
          # The following extension list based on the one from
          # <https://github.com/laravel/framework/blob/8.x/.github/workflows/tests.yml>.
          extensions: 'dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd'
          php-version: '8.0'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Set up SSH gubbins'
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ASSETS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: 'Ensure project builds and run all linting and testing tasks'
        run: './bin/task ci'
